runner = "qemu-system-x86_64"

[disks]
boot = "target/x86_64-custom/release/boot-bios-cashew_kernel.img"
hdb = "sfat.img"

[machine]
memory = "256M"
tty = "stdio"
wait_for_gdb = false
nic = "rtl8139"
